### ISSUE TITLE
tSNE matlab error

### ISSUE THREAD

**Issue by cannasw** [sidhomj/ExCYT#1]
Using matlab R2017b on mac. Able to load .fcs files, gate populations, and select parameters. When I press "t-SNE" button, I get below error. Must be something with my matlab config bc others have had no trouble working with same .fcs file.

Error using tsne
Too many input arguments.

Error in FlowGUI>tnsebutton_Callback (line 322)
Y=tsne(y,'Standardize',normalizetsne,'Distance',handles.Distance_Measure.String{handles.Distance_Measure.Value},'Perplexity',str2num(handles.Perplexity.String));

Error in gui_mainfcn (line 95)
        feval(varargin{:});

Error in FlowGUI (line 42)
    gui_mainfcn(gui_State, varargin{:});

Error in
matlab.graphics.internal.figfile.FigFile/read>@(hObject,eventdata)FlowGUI('tnsebutton_Callback',hObject,eventdata,guidata(hObject)) 
Error while evaluating UIControl Callback.

**Comment by sidhomj** [comment]
hmm, can you try updating to MATLAB 2018b?

**Comment by cannasw** [comment]
got it working by switching to 2018, not sure why, but some issues with
some .fcs files being compatible and others not.
thanks
